/**
 * Vendors the Open77 wiki into this repository.
 *
 * The documentation is authored in the platform repository (`open77-base`,
 * under `wiki/`) because it has to stay next to the code it documents. This
 * website is a separate repository deployed on its own, so the content is
 * copied in and committed: the build then needs no access to the platform
 * checkout, and every documentation change arrives as a reviewable diff.
 *
 * The script writes `content/docs/_manifest.json` recording the origin, byte
 * size and SHA-256 of every file it copied. `--check` re-runs the comparison
 * without writing, which is what CI should call to detect drift.
 *
 * Usage:
 *   node scripts/sync-wiki.mjs [--from ../base/wiki] [--check]
 */

import { readFile, writeFile, mkdir, readdir, rm } from "node:fs/promises";
import { existsSync } from "node:fs";
import { createHash } from "node:crypto";
import path from "node:path";
import process from "node:process";

import { EXCLUDED_GUIDES, isExcluded } from "./wiki-exclusions.mjs";

const DEFAULT_SOURCE = path.join("..", "base", "wiki");
const DOCS_OUT = path.join("content", "docs");
const API_OUT = path.join("content", "api");


function parseArgs(argv) {
  const args = { from: DEFAULT_SOURCE, check: false };
  for (let i = 0; i < argv.length; i += 1) {
    if (argv[i] === "--from") args.from = argv[++i] ?? args.from;
    else if (argv[i] === "--check") args.check = true;
  }
  return args;
}

function sha256(text) {
  return createHash("sha256").update(text).digest("hex");
}

/** First `# ` heading, which the wiki uses as the canonical page title. */
function extractTitle(markdown, fallback) {
  const match = markdown.match(/^#\s+(.+)$/m);
  return match ? match[1].trim() : fallback;
}

async function collectMarkdown(sourceDir) {
  const entries = await readdir(sourceDir, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    if (!entry.isFile() || !entry.name.endsWith(".md")) continue;
    if (isExcluded(entry.name)) continue;
    files.push(entry.name);
  }
  return files.sort();
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const sourceDir = path.resolve(args.from);

  if (!existsSync(sourceDir)) {
    // The vendored content is committed precisely so a build needs no platform
    // checkout, so its absence is a normal deployment state rather than an
    // error. Drift cannot be judged without the reference: skip instead of
    // failing, so `--check` is safe to wire into a general verification gate.
    if (args.check) {
      console.log(
        `sync-wiki: no wiki source at ${sourceDir} — skipping the drift check.\n` +
          "  Pass --from <path-to-open77-base/wiki> to check against a checkout elsewhere.",
      );
      return;
    }
    throw new Error(
      `wiki source not found at ${sourceDir}\n` +
        "Pass --from <path-to-open77-base/wiki> if the platform checkout lives elsewhere.",
    );
  }

  const markdownFiles = await collectMarkdown(sourceDir);
  if (markdownFiles.length === 0) {
    throw new Error(`no markdown guides found in ${sourceDir}`);
  }

  const apiSource = path.join(sourceDir, "data", "api.json");
  if (!existsSync(apiSource)) {
    throw new Error(
      `API reference data not found at ${apiSource}\n` +
        "Run `python wiki/tools/extract-api.py --json` in the platform repository first.",
    );
  }

  const records = [];
  const writes = [];

  for (const name of markdownFiles) {
    const text = await readFile(path.join(sourceDir, name), "utf8");
    const normalised = text.replace(/\r\n/g, "\n");
    const slug = name === "README.md" ? "index" : name.replace(/\.md$/, "");
    records.push({
      source: `wiki/${name}`,
      target: `${DOCS_OUT}/${name}`.replace(/\\/g, "/"),
      slug,
      title: extractTitle(normalised, slug),
      bytes: Buffer.byteLength(normalised, "utf8"),
      sha256: sha256(normalised),
    });
    writes.push({ file: path.join(DOCS_OUT, name), text: normalised });
  }

  const apiText = (await readFile(apiSource, "utf8")).replace(/\r\n/g, "\n");
  const apiEntries = JSON.parse(apiText);
  if (!Array.isArray(apiEntries)) {
    throw new Error("api.json is expected to be an array of API entries");
  }
  records.push({
    source: "wiki/data/api.json",
    target: `${API_OUT}/api.json`.replace(/\\/g, "/"),
    entries: apiEntries.length,
    bytes: Buffer.byteLength(apiText, "utf8"),
    sha256: sha256(apiText),
  });
  writes.push({ file: path.join(API_OUT, "api.json"), text: apiText });

  const manifest = {
    $comment:
      "Generated by scripts/sync-wiki.mjs. Do not edit by hand — edit the wiki in " +
      "the open77-base repository and re-run `npm run sync:wiki`.",
    source: "https://github.com/Open2077/open77-base",
    sourcePath: "wiki",
    syncedAt: new Date().toISOString(),
    guides: records.filter((record) => "slug" in record).length,
    apiEntries: apiEntries.length,
    files: records,
  };

  if (args.check) {
    let drift = 0;
    for (const write of writes) {
      const current = existsSync(write.file) ? await readFile(write.file, "utf8") : null;
      if (current !== write.text) {
        drift += 1;
        console.error(`out of date: ${write.file.replace(/\\/g, "/")}`);
      }
    }
    if (drift > 0) {
      throw new Error(`${drift} vendored file(s) differ from the wiki — run \`npm run sync:wiki\``);
    }
    console.log(`up to date: ${manifest.guides} guides, ${manifest.apiEntries} API entries`);
    return;
  }

  // Drop guides that were removed upstream so deletions propagate.
  if (existsSync(DOCS_OUT)) {
    const keep = new Set(markdownFiles);
    for (const entry of await readdir(DOCS_OUT, { withFileTypes: true })) {
      if (entry.isFile() && entry.name.endsWith(".md") && !keep.has(entry.name)) {
        await rm(path.join(DOCS_OUT, entry.name));
        console.log(`removed stale guide: ${entry.name}`);
      }
    }
  }

  await mkdir(DOCS_OUT, { recursive: true });
  await mkdir(API_OUT, { recursive: true });
  for (const write of writes) {
    await writeFile(write.file, write.text, "utf8");
  }
  await writeFile(
    path.join(DOCS_OUT, "_manifest.json"),
    `${JSON.stringify(manifest, null, 2)}\n`,
    "utf8",
  );

  console.log(`synced ${manifest.guides} guides and ${manifest.apiEntries} API entries`);
  for (const [name, reason] of EXCLUDED_GUIDES) {
    console.log(`  held back: ${name} — ${reason}`);
  }
  console.log(`  from ${sourceDir}`);
  const totalKb = (
    records.reduce((sum, record) => sum + record.bytes, 0) / 1024
  ).toFixed(1);
  console.log(`  ${totalKb} KB written to ${DOCS_OUT} and ${API_OUT}`);
}

main().catch((error) => {
  console.error(`sync-wiki: ${error.message}`);
  process.exitCode = 1;
});
